Topics:
  - "US Politics"
  - "Global Politics"
  - "Economics" 
  - "AI"
  - "Machine Learning"
  - "Technology"
  - "European Football"
  - "US Sports"
  - "Trump"
  - "US Stocks"
  - "Eurozone Stocks"
  - "US Dollar"
  - "EU"
  - "UK"
  - "China"
  - "South Africa"
  # - "Currenty updates (coming soon)"